---
# tasks file for ulogd2
- name: Install ulogd2 package
  ansible.builtin.apt:
    pkg: ulogd2
    state: present
    update_cache: yes
    cache_valid_time: 3600
  become: yes

- name: Configure ulogd2
  template:
    src: "{{ ulogd2_conf_template }}"
    dest: "{{ ulogd2_conf_dest }}"
    mode: "0600"
  become: yes
  notify:
    - restart ulogd2